# headers and icon 
title: ernani hazbolatow
info: clsjd'26 @ uva/vu
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
